functionsDirectory = "/Users/randyfox/Desktop/hotrod-happenings/hotrod-vision/netlify/functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/randyfox/Desktop/hotrod-happenings/hotrod-vision"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "/Users/randyfox/Desktop/hotrod-happenings/hotrod-vision/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[dev]
port = 8888.0
targetPort = 5173.0

[functions]

[functions."*"]